// This file is AUTO-GENERATED by the Whitehall compiler
// DO NOT EDIT MANUALLY

package com.example.myapp

import kotlinx.serialization.Serializable

sealed interface Routes {
  @Serializable
  object Home : Routes

  sealed interface Posts : Routes {
    @Serializable
    object Index : Posts

    @Serializable
    data class Detail(val id: String) : Posts
  }

  @Serializable
  data class Profile(val id: String) : Routes
}

// Generated NavHost
@Composable
fun AppNavigation() {
  val navController = rememberNavController()

  NavHost(navController, startDestination = Routes.Home) {
    // Home route: src/routes/+page.wh
    composable<Routes.Home> {
      HomePage()
    }

    // Posts index route: src/routes/posts/+page.wh
    composable<Routes.Posts.Index> {
      PostsIndexPage()
    }

    // Post detail route: src/routes/posts/[id]/+page.wh
    composable<Routes.Posts.Detail> { backStackEntry ->
      val route = backStackEntry.toRoute<Routes.Posts.Detail>()
      PostDetailPage(id = route.id)
    }

    // Profile route: src/routes/profile/[id]/+page.wh
    composable<Routes.Profile> { backStackEntry ->
      val route = backStackEntry.toRoute<Routes.Profile>()
      ProfilePage(id = route.id)
    }
  }
}
