// Auto-generated by Whitehall FFI (Rust)
// DO NOT EDIT MANUALLY

use jni::JNIEnv;
use jni::objects::{JClass, JString, JObject};
use jni::sys::*;

#[no_mangle]
pub extern "system" fn Java_com_example_fficpprust_ffi_subtract(
    env: JNIEnv,
    _class: JClass,
    a: jint,
    b: jint
) -> jint {
    crate::subtract(a, b)
}

#[no_mangle]
pub extern "system" fn Java_com_example_fficpprust_ffi_divide(
    env: JNIEnv,
    _class: JClass,
    a: jdouble,
    b: jdouble
) -> jdouble {
    crate::divide(a, b)
}

#[no_mangle]
pub extern "system" fn Java_com_example_fficpprust_ffi_modulo(
    env: JNIEnv,
    _class: JClass,
    a: jint,
    b: jint
) -> jint {
    crate::modulo(a, b)
}

#[no_mangle]
pub extern "system" fn Java_com_example_fficpprust_ffi_isEven(
    env: JNIEnv,
    _class: JClass,
    n: jint
) -> jboolean {
    crate::is_even(n) as jboolean
}

