// Auto-generated by Whitehall FFI (Rust)
// DO NOT EDIT MANUALLY

use jni::JNIEnv;
use jni::objects::{JClass, JString, JObject};
use jni::sys::*;

#[no_mangle]
pub extern "system" fn Java_com_example_ffirust_ffi_add(
    env: JNIEnv,
    _class: JClass,
    a: jint,
    b: jint
) -> jint {
    crate::add(a, b)
}

#[no_mangle]
pub extern "system" fn Java_com_example_ffirust_ffi_multiply(
    env: JNIEnv,
    _class: JClass,
    a: jint,
    b: jint
) -> jint {
    crate::multiply(a, b)
}

#[no_mangle]
pub extern "system" fn Java_com_example_ffirust_ffi_divide(
    env: JNIEnv,
    _class: JClass,
    a: jdouble,
    b: jdouble
) -> jdouble {
    crate::divide(a, b)
}

#[no_mangle]
pub extern "system" fn Java_com_example_ffirust_ffi_isPositive(
    env: JNIEnv,
    _class: JClass,
    n: jint
) -> jboolean {
    crate::is_positive(n) as jboolean
}

