// Rust FFI Example: Simple Math Operations
//
// Functions with #[ffi] attribute are automatically exposed
// to Whitehall/Kotlin code. No JNI boilerplate needed!

use whitehall::ffi;

#[ffi]
pub fn add(a: i32, b: i32) -> i32 {
    a + b
}

#[ffi]
pub fn multiply(a: i32, b: i32) -> i32 {
    a * b
}

#[ffi]
pub fn divide(a: f64, b: f64) -> f64 {
    if b == 0.0 {
        return 0.0; // Simple error handling
    }
    a / b
}

#[ffi]
pub fn is_positive(n: i32) -> bool {
    n > 0
}

// This function is NOT exported (private, not public)
fn helper(x: i32) -> i32 {
    x * 2
}


// JNI bridge module (generated by Whitehall FFI)
mod jni_bridge;
